# Generated by Django 2.0.5 on 2018-05-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='full_title',
            field=models.CharField(default='nothing', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='show_on_home_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
