# Generated by Django 2.0.4 on 2018-05-16 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20180510_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfile',
            name='auth_required',
        ),
    ]
