# Generated by Django 2.0.5 on 2018-05-23 14:45

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfile',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='E:\\projects\\static_cdn\\protected_media'), upload_to=products.models.upload_file_loc, verbose_name=products.models.Product),
        ),
    ]
